// GENERATED by scripts/build-legal.ts from scripts/data/legal/privacy_panameer.md.
// Do not edit by hand — edit the source text and re-run `npm run legal:build`.
// DRAFT CONTENT, PENDING LEGAL REVIEW. See brief_legal_pages_content.
import type { LegalNode } from "@/content/legal/types";

export const PRIVACY_DOC: LegalNode[] = [
  {
    "t": "p",
    "text": "This Privacy Policy explains how and why Panameer collects, uses, and shares personal information when you interact with or use our Site or Service. It also includes any information Panameer collects offline in connection with the Service, which we may combine with information from the Site and Service."
  },
  {
    "t": "p",
    "text": "When we say “Panameer”, we mean Panameer Global LLC, and any of its affiliates, including Payment Escrow, Inc. When we say “Site”, we mean www.panameer.com, and when we say “Service”, we mean the Site plus any websites, features, applications, widgets, or online services owned or controlled by Panameer."
  },
  {
    "t": "p",
    "text": "As part of the Service, Panameer provides a marketplace which facilitates interactions between users."
  },
  {
    "t": "p",
    "text": "Users of the Service may be Clients, Providers, Agencies, or Site Visitors (as each is defined in the User Agreement). This Privacy Policy applies to Panameer’s processing of personal information of Users where Panameer determines the purposes and means of processing. It does not apply to processing of information by Users themselves, who may be controllers of the personal information they access through the Service. For information about how Users process your personal information, please contact them directly."
  },
  {
    "t": "p",
    "text": "Accessibility: This Privacy Policy uses industry-standard technologies and was developed in connection with the World Wide Web Consortium's Web Content Accessibility Guidelines, version 2.1. If you wish to print this policy, please do so from your web browser or by saving the page as a PDF."
  },
  {
    "t": "h2",
    "text": "1. INFORMATION COLLECTION"
  },
  {
    "t": "h3",
    "text": "a. Information You Provide to Us"
  },
  {
    "t": "p",
    "text": "When you use the Service, you may provide us with information about you. This may include your name and contact information, financial information to make or receive payment for services obtained through the Panameer platform, or information to help us fill out tax forms. When you use the Service, we may also collect information related to your use of the Service and aggregate this with information about other users. This helps us improve our Services for you. You may also provide us with information about your contacts or friends if, for example, you’d like to add those contacts to a message room. Agencies may also provide us with information about Providers associated with the Agency."
  },
  {
    "t": "p",
    "text": "Depending upon our relationship with you, we may collect the following categories and types of personal information from and about you:"
  },
  {
    "t": "gap",
    "lines": 300
  },
  {
    "t": "h3",
    "text": "b. Non-Identifying Information and De-Identified Information"
  },
  {
    "t": "p",
    "text": "Non-Identifying Information/Usernames: We also may collect other information that does not identify you directly, such as zip codes, demographic data, information about your use of the Service, and general project-related data (“Non-Identifying Information”). We may combine information collected from Panameer users, whether they are registered or not (“Panameer Users”). In some cases, we may render Personal Information (generally, email address) into a form of NonIdentifying Information referred to in this Privacy Policy as “Hashed Information.” This is typically accomplished using a mathematical process (commonly known as a hash function) to convert information into a code. While the code does not identify you directly, it may be used by Panameer’s partners to connect your activity and interests."
  },
  {
    "t": "p",
    "text": "Combination of Personal and Non-Identifying Information: We may combine your Personal Information with Non-Identifying Information, but Panameer will treat the combined information as Personal Information."
  },
  {
    "t": "p",
    "text": "De-Identified Information: We may also de-identify or aggregate information and convert it into non-personal information so that it can no longer reasonably be used to identify you (“DeIdentified Information”). We may use De-Identified Information for any of the purposes described in the “We Use Information We Collect” section below. We will maintain and use De-Identified"
  },
  {
    "t": "p",
    "text": "Information in de-identified form and will not attempt to reidentify the information, except to confirm our de-identification processes or unless required by law."
  },
  {
    "t": "h3",
    "text": "c. Information Collected Automatically"
  },
  {
    "t": "p",
    "text": "Like other online companies, we receive technical information when you use our Services. We use these technologies to analyze how people use the Service, to improve how our Site functions, to save your login information for future sessions, and to serve you with advertisements that may interest you. Panameer and its partners use cookies or similar technologies to analyze trends, administer the website, track users’ movement around the website, the desktop app, and the mobile app, and to gather demographic information about our user base as a whole. The technology used to collect information automatically from Panameer Users may include cookies, web beacons, and embedded scripts. In addition, we and our marketing partners, affiliates, analytics, and service providers may use a variety of other technologies (such as tags) that collect similar information for security and fraud detection purposes and we may use third parties to perform these services on our behalf."
  },
  {
    "t": "p",
    "text": "For further information on cookies and how they are used for the Service, please visit our Cookie Policy at www.panameer.com/legal#cookie-policy."
  },
  {
    "t": "h3",
    "text": "d. Work Diaries and Work View"
  },
  {
    "t": "p",
    "text": "With your permission, we collect information about a Provider’s work for a Client, including automatically collected information about work on a particular project. If a Provider enables Work Diaries, we will share Work Diaries with the relevant Client and Agency. We tell Providers when we are capturing information for the Work Diary and allow Providers to block such data sharing."
  },
  {
    "t": "p",
    "text": "As part of the Service, when enabled by a Provider, we collect information about a Provider’s work on a project for a Client, including information that may be considered personal information. This feature is known as Work Diary. Work Diaries include information provided by the Provider, such as a memo, as well as automatically gathered information about work on a project, such as number of mouseclicks and keyboard strokes and regularly taken screenshots (which may include a webcam picture of you if you have enabled this feature in your settings). In order to use Work Diaries, you must download and install the Team App software from www.panameer.com ."
  },
  {
    "t": "p",
    "text": "We will share information contained in Work Diaries with the relevant Client and with any manager or administrator of any applicable Provider Agency, and use Work Diary information as otherwise described in this Privacy Policy. We inform Providers each time we capture information for Work Diary."
  },
  {
    "t": "p",
    "text": "As set forth in our Terms of Service, End User License Agreement, and help pages on the Site, a Provider may choose to block or delete the screen shot and associated data for a recorded work interval, but then the Provider may not be paid for that work interval."
  },
  {
    "t": "h3",
    "text": "e. Analytics Providers, Ad Servers and Similar Third Parties"
  },
  {
    "t": "p",
    "text": "We may work with advertising agencies and vendors who use technology to help us understand how people use our Site. These vendors may use technologies to serve you advertisements that may interest"
  },
  {
    "t": "p",
    "text": "you. Depending on your location, you may have the right to opt out of receiving certain interest-based advertising. See the ‘Your Choices and Rights Section’ below for more information."
  },
  {
    "t": "p",
    "text": "Panameer works with ad networks, ad agencies, analytics service providers and other vendors to provide us with information regarding traffic on the Service, to serve our advertisements on other websites, within mobile apps and elsewhere online; and to provide us with information regarding the use of the Service and the effectiveness of our advertisements. Our service providers may collect certain information about your visits to and activity on the Service as well as other websites or services, they may set and access their own tracking technologies on your device (including cookies, pixels, and web beacons), and may use that information to show you targeted advertisements. Some of these parties may collect Personal Information when you visit the Service or other online websites and services. We may also share certain Non-Identifying Information with these parties, including Hashed Information, in connection with the services they provide to us."
  },
  {
    "t": "h3",
    "text": "f. Do Not Track Signals"
  },
  {
    "t": "p",
    "text": "Please note that your browser setting may allow you to automatically transmit a “Do Not Track” signal to websites and online services you visit. Panameer does not generally alter its practices when it receives a “Do Not Track” signal from a visitor’s browser. To find out more about “Do Not Track,” please visit http://www.allaboutdnt.com."
  },
  {
    "t": "h3",
    "text": "g. Children"
  },
  {
    "t": "p",
    "text": "The Service is general audience and intended for users 18 and older. We do not knowingly collect Personal Information from anyone younger than age 18. If we become aware that a child younger than 18 has provided us with Personal Information, we will use commercially reasonable efforts to delete such information from our files. If you are the parent or legal guardian of a child younger than age 18 and believe that Panameer has collected Personal Information from your child, please contact us at: legalnotices@panameer.com."
  },
  {
    "t": "h2",
    "text": "2. USE OF INFORMATION"
  },
  {
    "t": "p",
    "text": "We, along with our service providers, may use your data for the purposes described below. As part of these purposes, your data may be processed using Artificial Intelligence technologies (“AI”) including AI that generates images, text, audio, or video from user inputs (generative AI). We may use your data for the following purposes:"
  },
  {
    "t": "h3",
    "text": "a. We Use Information We Collect:"
  },
  {
    "t": "p",
    "text": "To develop, provide, and improve the Service, complete your transactions, address your inquiries, process your registration, verify the information you provide is valid, and for compliance and internal business purposes."
  },
  {
    "t": "p",
    "text": "To administer and develop our business relationship with you and, if applicable, the corporation or other legal entity you represent."
  },
  {
    "t": "p",
    "text": "For the purposes disclosed at the time you provide your information, with your consent, and as further described in this Privacy Policy."
  },
  {
    "t": "p",
    "text": "To contact you with administrative communications and Panameer newsletters, marketing or promotional materials (on behalf of Panameer or third parties) and other information that may be of interest to you. To tailor content we display to you and offers we may present to you, both on the Service and elsewhere online."
  },
  {
    "t": "p",
    "text": "To prepare internal statistics reports."
  },
  {
    "t": "p",
    "text": "To honor our contractual commitments, or to take steps at Users' request in anticipation of entering into a contract with them."
  },
  {
    "t": "p",
    "text": "For our legitimate interests. In many cases, we handle Personal Information on the grounds that it furthers our legitimate interests in commercial activities, such as the following, in ways that are not overridden by the interests or fundamental rights and freedoms of the affected individuals: Providing our Site and Service."
  },
  {
    "t": "p",
    "text": "Detecting security incidents, protecting against malicious, deceptive, fraudulent or illegal activity, and prosecuting those responsible for that activity."
  },
  {
    "t": "p",
    "text": "Measuring interest and engagement in our Services."
  },
  {
    "t": "p",
    "text": "Short-term, transient use, such as contextual customization of ads."
  },
  {
    "t": "p",
    "text": "Improving, upgrading or enhancing our Services."
  },
  {
    "t": "p",
    "text": "Developing new products and services."
  },
  {
    "t": "p",
    "text": "Ensuring internal quality control and safety."
  },
  {
    "t": "p",
    "text": "Authenticating and verifying individual identities."
  },
  {
    "t": "p",
    "text": "Debugging to identify and repair errors with our Services."
  },
  {
    "t": "p",
    "text": "Auditing relating to interactions, transactions and other compliance activities."
  },
  {
    "t": "p",
    "text": "Enforcing our agreements and policies."
  },
  {
    "t": "p",
    "text": "Analyzing and improving our business."
  },
  {
    "t": "p",
    "text": "Communications, including marketing and responding to your inquiries about our services."
  },
  {
    "t": "p",
    "text": "Addressing information security needs and protecting our Users, Panameer, and others."
  },
  {
    "t": "p",
    "text": "Managing legal issues."
  },
  {
    "t": "p",
    "text": "Across Panameer Services and Features. As part of providing an integrated platform experience, we may use personal information collected through one feature or interaction on the Service to support other features or offerings within the Service. For example, data from your profile, proposals, communications, or feedback may help inform other parts of the Service, such as talent recommendations, search results, or generative AI-powered tools."
  },
  {
    "t": "p",
    "text": "To enforce and comply with the law, including to conduct an investigation, to protect the property and rights of Panameer or a third party, to protect the safety of the public or any person, or to prevent or stop activity we may consider to be, or to pose a risk of being, illegal, fraudulent, unethical or legally actionable activity."
  },
  {
    "t": "p",
    "text": "To Comply with Legal Obligations. We need to use and disclose Personal Information in certain ways to comply with our legal obligations."
  },
  {
    "t": "h3",
    "text": "b. Public Content on the Platform:"
  },
  {
    "t": "p",
    "text": "Some parts of the Service allow you to share personal information publicly, such as when you create a public profile, post a public job, submit proposals that include visible content, or leave feedback (“Public Content”). When you choose to make information public through the Service, it may be indexed by search engines, accessible to other users or third parties, and reused within other parts of the Service, including features that help connect Clients and Providers or generate insights and recommendations."
  },
  {
    "t": "p",
    "text": "Please note that information you choose to make public may be accessed, copied, or used by others in ways we do not control. Panameer cannot guarantee how third parties or other users will use such publicly available information. You should not include information you consider sensitive or confidential in areas of the platform designated as public."
  },
  {
    "t": "p",
    "text": "Panameer may use Public Content to power, develop, or improve other services and features. For example, public job posts and profiles may be used to enhance search results, match recommendations, or provide aggregated insights."
  },
  {
    "t": "h2",
    "text": "3. DATA RETENTION"
  },
  {
    "t": "p",
    "text": "Unless you request that we delete certain information (see Your Choices and Rights below), we will only retain your personal information for as long as is necessary to fulfill the purposes for which it was collected, including for the purposes of satisfying any legal, regulatory, accounting, or reporting requirements, as well as ongoing fraud prevention, backup, and business continuity purposes."
  },
  {
    "t": "h2",
    "text": "4. INFORMATION SHARING AND DISCLOSURE"
  },
  {
    "t": "p",
    "text": "We do not sell your Personal Information for monetary consideration, and we do not share your Personal Information with third parties for those third parties’ marketing purposes unless we first provide you with the opportunity to opt-in to or opt-out of such sharing. However, we may use technologies on our Site for the purposes of advertising or marketing to you and understanding how you interact with our ads. This may be considered a “sale” or “sharing” of personal information for targeted advertising under applicable data protection laws. Depending on your location, you may have the right to opt out of this sale or sharing (see Your Choices and Rights below)."
  },
  {
    "t": "p",
    "text": "We may also share information we have collected about you, including Personal Information, as disclosed at the time you provide your information, with your consent, as otherwise described in this Privacy Policy, or for the following business or commercial purposes:"
  },
  {
    "t": "gap",
    "lines": 148
  },
  {
    "t": "h2",
    "text": "5. YOUR CHOICES AND RIGHTS"
  },
  {
    "t": "p",
    "text": "Residents of certain locations may have choices and rights associated with your personal information, including opting out of targeted advertising or other disclosures to third parties, or the right to have an authorized agent submit certain requests on your behalf. You or your authorized agent may request that Panameer honor these rights by: submitting a request here; or Calling us toll-free at 866-262-4478"
  },
  {
    "t": "p",
    "text": "Non-Discrimination: You will not receive any discriminatory treatment by us for the exercise of your privacy rights."
  },
  {
    "t": "p",
    "text": "Verifying Your Request: Only you, or a person that you authorize to act on your behalf, may make a request related to your personal information. In the case of access and deletion, your request must be verifiable before we can fulfill such request. Verifying your request will require you to provide sufficient information for us to reasonably verify that you are the person about whom we collected personal information or a person authorized to act on your behalf. We will only use the personal information that you have provided in a verifiable request in order to verify your request. We cannot respond to your request or provide you with personal information if we cannot verify your identity or authority."
  },
  {
    "t": "p",
    "text": "Please note that we may charge a reasonable fee or refuse to act on a request if such request is excessive, repetitive or manifestly unfounded."
  },
  {
    "t": "p",
    "text": "For Individuals Located in the European Economic Area (EEA), United Kingdom (UK) or Switzerland: You have a number of rights under applicable data protection laws in relation to your personal information. Under certain circumstances, you have the right to: Have access to your personal information by submitting a request to us; Have your personal information deleted; Have your personal information corrected if it is wrong;"
  },
  {
    "t": "p",
    "text": "Have the processing of your personal information restricted; Object to further processing of your personal information, including to object to marketing from us; Make a data portability request; Withdraw any consent you have provided to us; Restrict certain automatic processing of your personal information; and Complain to the appropriate Supervisory Authority."
  },
  {
    "t": "p",
    "text": "To exercise any of these rights, please contact us as outlined above."
  },
  {
    "t": "p",
    "text": "For California Residents “Shine the Light” and “Eraser” Laws: Residents of the State of California may request a list of all third parties to which we have disclosed certain information during the preceding year for those third parties’ direct marketing purposes."
  },
  {
    "t": "p",
    "text": "California Consumer Privacy Act (CCPA)/California Privacy Rights Act (CPRA): The CCPA, as amended by the CPRA, provides California residents and/or their authorized agents with specific rights regarding the collection and processing of their personal information."
  },
  {
    "t": "p",
    "text": "Your Right to Know: California residents have the right to request that we disclose the following information to you about our collection and use of your personal information over the past twelve (12) months. We may ask you to provide certain information to identify yourself so that we may compare it with our records in order to verify your request. Upon verification, we will disclose to you: 1. The categories of personal information we have collected about you."
  },
  {
    "t": "p",
    "text": "2. The categories of sources for the personal information we have collected about you."
  },
  {
    "t": "p",
    "text": "3. The specific pieces of personal information we have collected about you."
  },
  {
    "t": "p",
    "text": "4. Our business or commercial purpose for collecting or “selling” your personal information as defined by the CCPA."
  },
  {
    "t": "p",
    "text": "5. The categories of third parties to whom we have sold or shared your personal information, if any, and the categories of personal information that we have shared with each third-party recipient."
  },
  {
    "t": "p",
    "text": "Your Right to Opt-Out of “Sale” or “Sharing” of Personal Information: California residents have the right to opt-out of the “sale” or “sharing” of their personal information as defined by the CCPA. Where we are “sharing” your personal information with third parties for the purposes of cross-context behavioral advertising, you may opt-out of such sharing at any time by clicking on the “Your Privacy Choices” link located in the footer of our website. Global Privacy Control (GPC) is a browser-based signal that you can use to inform websites of your privacy preferences regarding ad trackers, and which acts as a mechanism for opting out of the “sale” or “sharing” of personal information. If you have the GPC signal"
  },
  {
    "t": "p",
    "text": "turned on in your web browser, it may impact the functionality of the Site, but we honor the GPC signal on a per-browser basis as an opt-out of the “sale” or “sharing” of personal information in accordance with and to the extent required by applicable law."
  },
  {
    "t": "p",
    "text": "Please note that we do not knowingly “sell” the personal information of any individuals under the age of 18."
  },
  {
    "t": "p",
    "text": "Your Right to Limit Use of Sensitive Personal Information: California residents may have the right to request that businesses limit the use of any sensitive personal information to those uses which are necessary to perform the Services or for other specifically-enumerated business purposes under the CCPA, as amended by the CPRA. Please note that we do not use sensitive personal information other than as necessary to perform the Services or as specifically permitted under the CCPA."
  },
  {
    "t": "p",
    "text": "Your Right to Delete: California residents have the right to request that we delete any of the personal information collected from you and retained by us, subject to certain exceptions. We may ask you to provide certain information to identify yourself so that we may compare it with our records in order to verify your request. Once your request is verified and we have determined that we are required to delete the requested personal information in accordance with the CCPA, we will delete, and direct our service providers to delete your personal information from their records. Your request to delete personal information that we have collected may be denied if we conclude it is necessary for us to retain such personal information under one or more of the exceptions listed in the CCPA."
  },
  {
    "t": "p",
    "text": "Your Right to Correct: Under the CCPA, as amended by the CPRA, California residents have the right to request that we correct any inaccurate personal information we maintain about you, taking into account the nature of the personal information and the purposes for which we are processing such personal information. We will use commercially reasonable efforts to correct such inaccurate personal information about you."
  },
  {
    "t": "p",
    "text": "Non-Discrimination: You will not receive any discriminatory treatment by us for the exercise of your privacy rights conferred by the CCPA."
  },
  {
    "t": "p",
    "text": "To opt out of the “sale” or “sharing” of your personal information, see “Your Right to Opt-Out of ‘Sale’ or ‘Sharing’ of Personal Information” above. To exercise any of the other rights listed here, please contact us as outlined in the first paragraph of this Section 5 above."
  },
  {
    "t": "p",
    "text": "Notice for Nevada Residents Under Nevada law, certain Nevada residents may opt out of the sale of “personally identifiable information” for monetary consideration to a person for that person to license or sell such information to additional persons. “Personally identifiable information” includes first and last name, address, email address, phone number, Social Security Number, or an identifier that allows a specific person to be contacted either physically or online."
  },
  {
    "t": "p",
    "text": "We do not engage in such activity; however, if you are a Nevada resident who has purchased or leased goods or services from us, you may submit a request to opt out of any potential future sales under Nevada law by emailing privacyrequests@panameer.com. Please note we will take reasonable steps to verify your identity and the authenticity of the request. Once verified, we will maintain your request in the event our practices change."
  },
  {
    "t": "p",
    "text": "Residents of Certain Other States The laws of your state of residence (“Applicable State Law”) may provide you with certain rights, including the following: Your Right to Confirm and Access: You have the right to confirm whether we are processing personal information about you and access the personal information we process about you."
  },
  {
    "t": "p",
    "text": "Your Right to Portability: You have the right to obtain a copy of the personal information we maintain and process about you in a portable and, to the extent technically feasible, readily-usable format."
  },
  {
    "t": "p",
    "text": "Your Right to Delete: You have the right to request that we delete the personal information we maintain or process about you."
  },
  {
    "t": "p",
    "text": "Your Right to Correct: You have the right to request that we correct inaccuracies in the personal information we maintain or process about you, taking into consideration the nature and purpose of such processing."
  },
  {
    "t": "p",
    "text": "Your Rights to Opt-Out: You have the right to opt-out of certain types of processing of personal information, including: Opt-Out of the “sale” of personal information as defined by Applicable State Law; Opt-Out of sharing of personal information for targeted advertising by us; Opt-Out of automated profiling for the purposes of making decisions that produce legal or similarly significant effects."
  },
  {
    "t": "p",
    "text": "To opt out of the “sale” of your personal information, or the sharing of your personal information for targeted advertising, see the “Opting Out of Targeted Advertising” section below. To exercise any of the other rights listed here, please contact us as outlined in the first paragraph of this Section 5 above."
  },
  {
    "t": "p",
    "text": "Opting Out of Targeted Advertising Depending on your location, you may have the right to opt out of the “sale” of your personal information or sharing of your personal information for targeted advertising from Panameer by clicking on the “Your Privacy Choices” link located in the footer of our website."
  },
  {
    "t": "p",
    "text": "Global Privacy Control (GPC) is a browser-based signal that you can use to inform websites of your privacy preferences regarding ad trackers, and which acts as a mechanism for opting out of the “sale” of personal information or sharing of personal information for targeted advertising. If you have the GPC turned on in your web browser, it may impact the functionality of the Site, but we honor the GPC signal on a per-browser basis as an opt-out of the “sale” of personal information or sharing of personal information for targeted advertising."
  },
  {
    "t": "p",
    "text": "You may also want to visit http://www.aboutads.info/choices/, which provides information regarding targeted advertising and offers an “opt-out” by participating companies in the Digital Advertising Alliance (DAA) Self-Regulatory Program. While we may use a variety of service providers to perform advertising services, some of these companies are members of the DAA. If you wish to submit a bulk opt-out of targeted advertising from such participating companies, click here (or if located in the"
  },
  {
    "t": "p",
    "text": "European Union, click here). You must opt out on each device and each browser where you want your choice to apply. If you choose to opt out, please note you will continue to receive advertisements, but they may be less relevant to you."
  },
  {
    "t": "p",
    "text": "Appeals Process & Other Concerns Certain information may be exempt from the rights described above under applicable law. If we deny your request in whole or in part, you may have the right to appeal the decision. In such circumstances, we will provide you with information regarding the appeals process. Depending on your location, you may also email legalnotices@panameer.com with the subject “Data Privacy Request Appeal” to provide us with details about why you are appealing the decision."
  },
  {
    "t": "p",
    "text": "If you have an unresolved privacy or data use concern that we have not addressed to your satisfaction, please contact our U.S.-based third-party dispute resolution provider free at https://feedbackform.truste.com/watchdog/request."
  },
  {
    "t": "h2",
    "text": "6. SECURITY"
  },
  {
    "t": "p",
    "text": "We take a number of steps to protect your data, but no security is guaranteed."
  },
  {
    "t": "p",
    "text": "Panameer takes reasonable steps to help protect and secure the information it collects and stores about Panameer Users. We maintain reasonable administrative, technical, and physical safeguards designed to protect personal information that we receive against accidental, unlawful, or unauthorized destruction, loss, alteration, access, disclosure or use."
  },
  {
    "t": "h2",
    "text": "7. CROSS-BORDER DATA TRANSFERS"
  },
  {
    "t": "p",
    "text": "Because we are a U.S. company, we process and store your information in the United States and our service providers may process and store it elsewhere."
  },
  {
    "t": "p",
    "text": "Panameer may transfer your personal information to a third party that is located in a jurisdiction other than the one from which we collected your personal information, including to countries that have not been deemed to have an adequate level of protection for the rights and freedoms of data subjects. If we do transfer your personal information to another jurisdiction, we will do so following due diligence and provided that the data recipient is subject to contractual agreements imposing obligations on it to ensure appropriate technical and organizational are implemented and maintained at all times to prevent the unauthorized and unlawful processing of personal information, and the accidental loss or destruction of, or damage to, personal information, consistent with our obligations under applicable data protection laws."
  },
  {
    "t": "p",
    "text": "We will use appropriate legal transfer mechanisms, including Standard Contractual Clauses, where required by law. To exercise any legal right to see copies of the data transfer mechanism documents that Panameer uses to transfer data to third parties, please contact us."
  },
  {
    "t": "h2",
    "text": "8. LINKS TO OTHER SITES"
  },
  {
    "t": "p",
    "text": "We may provide links to digital assets such as websites or applications of services that we do not own or operate (“third-party digital assets”). This Privacy Policy does not apply to data collected through any such third-party digital assets. Panameer is not responsible for the privacy practices of such third-party"
  },
  {
    "t": "p",
    "text": "digital assets. We encourage you to carefully review the privacy policies or statements applicable to any third-party digital assets you visit."
  },
  {
    "t": "h2",
    "text": "9. CHANGES TO THIS POLICY"
  },
  {
    "t": "p",
    "text": "We may change this Privacy Policy. If we make material changes, we will provide notice."
  },
  {
    "t": "p",
    "text": "This Privacy Policy is effective as of the date stated at the top of this page. Panameer may update this Privacy Policy at any time and any changes will be effective upon posting. By accessing or using the Service after we notify you of such changes to this Privacy Policy, you are deemed to have accepted such changes. Please refer back to this Privacy Policy on a regular basis."
  },
  {
    "t": "h2",
    "text": "10. CONTACT US"
  },
  {
    "t": "p",
    "text": "To request that Panameer honor any of the rights described in this Policy, contact us as described above in the Your Choices and Rights section."
  },
  {
    "t": "p",
    "text": "General Data Protection Regulation (GDPR) – European Representative Pursuant to Article 27 of the General Data Protection Regulation (GDPR), Panameer Inc. has appointed European Data Protection Office (EDPO) as its GDPR Representative in the EU. You can contact EDPO regarding matters pertaining to the GDPR: by using EDPO’s online request form: https://edpo.com/gdpr-data-request, or by writing to EDPO at Ground Floor, 71 Lower Baggot Street, Dublin, D02 P593, Ireland"
  },
  {
    "t": "p",
    "text": "UK General Data Protection Regulation (GDPR) - UK Representative Pursuant to Article 27 of the UK GDPR, Panameer Inc. has appointed EDPO UK Ltd as its UK GDPR representative in the UK. You can contact EDPO UK regarding matters pertaining to the UK GDPR: by using EDPO’s online request form: https://edpo.com/uk-gdpr-data-request, or by writing to EDPO UK at 8 Northumberland Avenue, London WC2N 5BY, United Kingdom"
  },
  {
    "t": "p",
    "text": "FADP Article 14 Representative Pursuant to Article 14 of the FADP, Panameer Inc. has appointed EDPO Switzerland as its Representative in Switzerland. You can contact EDPO Switzerland regarding matters pertaining to the FADP: by using EDPO Switzerland's online request form: https://edpo.com/swiss-data-request, or by writing to EDPO Switzerland at Rue de Lausanne 37, 1201 Geneva, Switzerland"
  },
  {
    "t": "p",
    "text": "If you have any questions about this Privacy Policy, please contact us at: https://support.panameer.com; By email to privacy@panameer.com;"
  },
  {
    "t": "p",
    "text": "by mail addressed to Panameer, Attn: Legal, 3490 S 4400 W #70008 West Valley City, UT 841209998, USA; or by phone at 866-262-4478."
  }
];
