// GENERATED by scripts/build-legal.ts from scripts/data/legal/tos_panameer.md.
// Do not edit by hand — edit the source text and re-run `npm run legal:build`.
// DRAFT CONTENT, PENDING LEGAL REVIEW. See brief_legal_pages_content.
import type { LegalNode } from "@/content/legal/types";

export const TERMS_DOC: LegalNode[] = [
  {
    "t": "p",
    "text": "This document explains the rules that keep our marketplace running."
  },
  {
    "t": "p",
    "text": "We call these rules our Terms of Use. They apply to panameer.com and all the websites and apps we own or run. (And by we, we mean Panameer and our affiliates, which we may also refer to as us.)"
  },
  {
    "t": "p",
    "text": "These terms explain how we expect you to behave when you’re using Panameer – whether you’re a registered user or unregistered site visitor on our site."
  },
  {
    "t": "p",
    "text": "Please read these rules carefully: by using our site, you’re agreeing to follow them."
  },
  {
    "t": "p",
    "text": "When you see this"
  },
  {
    "t": "p",
    "text": "symbol, look for a simple summary for each section. We wrote these to help"
  },
  {
    "t": "p",
    "text": "you get a quick overview, but you'll need to read the sections completely to get all the details of what you're agreeing to."
  },
  {
    "t": "h2",
    "text": "1. About licenses and third party content"
  },
  {
    "t": "p",
    "text": "Here we’ve included the conditions for using our site, which we do our best to keep running smoothly (1.1). That means we have the right to stop people from using our site and services if needed (1.2)."
  },
  {
    "t": "p",
    "text": "You can’t use our intellectual property (1.3), but you can post your own content to Panameer. You’re responsible for this content (1.4), and equally, we’re not responsible for content you come across from other users (1.5). If you think someone is using something you’ve copyrighted, just let us know (1.6)."
  },
  {
    "t": "h3",
    "text": "1.1 We let you use our site and services"
  },
  {
    "t": "p",
    "text": "Technically, we’re giving you a ‘limited license’ to the site. Here’s what that means."
  },
  {
    "t": "p",
    "text": "We’re happy for you to access our website and services (known as the services). You’re free to have this access (or limited license) as long as you follow these terms of use and all of our other Terms of Service as they apply to you."
  },
  {
    "t": "p",
    "text": "We’ll do our best to make sure our services are safe and working as they should, but we can’t guarantee you’ll have access continuously. In fact, we might even stop providing certain features or the services completely, and don’t have to give notice if we do."
  },
  {
    "t": "h3",
    "text": "1.2 We can stop letting you use our services"
  },
  {
    "t": "p",
    "text": "We can take away your right to use our services at any time."
  },
  {
    "t": "p",
    "text": "If you violate our Terms of Use or other parts of our Terms of Service, we can take away your access to Panameer. Officially, this is called terminating your license, and if it happens, we’ll tell you and you must stop using our services immediately."
  },
  {
    "t": "h3",
    "text": "1.3 We keep the rights to our intellectual property"
  },
  {
    "t": "p",
    "text": "Using our services doesn’t mean you can use any of our trademarks or other intellectual property, like copyrights and patents. We keep all of our rights to our intellectual property, even though we let you use our services."
  },
  {
    "t": "p",
    "text": "Our logos and names are our trademarks and registered in certain jurisdictions. Any other product or company names, logos or similar marks and symbols you see on Panameer may be trademarked by our partners or other users like you."
  },
  {
    "t": "h3",
    "text": "1.4 You can use Panameer to share your content with the world"
  },
  {
    "t": "h4",
    "text": "1.4.1 You’re responsible for what you post"
  },
  {
    "t": "p",
    "text": "You’re responsible for how you use our site and anything you post on it. If someone makes a claim against us because of anything you put on the site, you agree to compensate us for our legal fees and expenses (the lawyers call this, ‘indemnification’)."
  },
  {
    "t": "p",
    "text": "When you post content on (or through) our site or give us content for posting, you agree that you’re completely responsible for that content and we’re not. You also agree to only post or give us content that: you have the right to post"
  },
  {
    "t": "p",
    "text": "is legal doesn’t violate anyone’s rights, including intellectual property rights."
  },
  {
    "t": "p",
    "text": "You acknowledge and agree that whoever posts content is responsible for any harm caused to anyone by that content – not Panameer – and that you’ll compensate and defend us, our partners, employees and representatives against any costs or legal or government action we have because of your content."
  },
  {
    "t": "h4",
    "text": "1.4.2 Other people have some rights to what you post"
  },
  {
    "t": "p",
    "text": "By posting content on the site, you give other people some rights to that content."
  },
  {
    "t": "p",
    "text": "Whenever you post content on our site, you give us and our affiliates a permanent right (called an ‘irrevocable and non-exclusive worldwide license’) to use, edit and share that content – across the world and without paying royalties. If your name, voice and image appear in content you post, we also might use those on the site or in our day-to-day business. For example, if you’re a provider, we might share your profile with clients we think could be a good match."
  },
  {
    "t": "p",
    "text": "You also give each user and site visitor the right to access and use your content through the site. They also have the right to use, copy and share your content – as long as they do it through the site, and follow both our Terms of Service and the law."
  },
  {
    "t": "p",
    "text": "We might show ads near your content and information, without compensating you. Depending on choices you make in your profile, we might also include your name or photo when promoting one of our features."
  },
  {
    "t": "h4",
    "text": "1.4.3 We’re open to your ideas"
  },
  {
    "t": "p",
    "text": "We’d love to hear your thoughts on improving Panameer. Here’s what happens when you share them."
  },
  {
    "t": "p",
    "text": "You can send us comments and suggestions about our services and ways to improve them. If you do, you’re agreeing your ideas are free and unsolicited, and you don’t expect or ask anything in return, unless we’ve specifically asked you for your ideas and offered something in return (we like to keep our word)."
  },
  {
    "t": "p",
    "text": "You agree we’re free to use, change and share the idea as we like, without being obligated to to give you anything for it. And if you do send us an idea, you also agree that this doesn’t affect our right to use similar or related ideas – including those we already have or get from others."
  },
  {
    "t": "h3",
    "text": "1.5 Third parties post on Panameer, too"
  },
  {
    "t": "p",
    "text": "Anyone else who uses our site is responsible for what they post or link on Panameer."
  },
  {
    "t": "p",
    "text": "We’re not responsible for the accuracy or reliability of any content shared by other people on our site, unless they’re officially working for us when they share or post the content. Any content represents the views of the person sharing it, not Panameer."
  },
  {
    "t": "p",
    "text": "Our site might also contain links or other access to third-party websites and applications. These sites and applications are owned and run by other parties, not Panameer. If we use a link or application that goes to"
  },
  {
    "t": "p",
    "text": "a third-party website, it doesn’t mean that we endorse it and you agree that you use it without our endorsement."
  },
  {
    "t": "h3",
    "text": "1.6 You can make a copyright complaint"
  },
  {
    "t": "p",
    "text": "If you think content on our site infringes your rights, you can ask to have it removed."
  },
  {
    "t": "p",
    "text": "We’re committed to following U.S. copyright and related laws and need site visitors and users to follow them as well. That means you can’t use our site to store or share anything that infringes anyone’s intellectual property rights, including their rights under U.S. copyright law."
  },
  {
    "t": "p",
    "text": "If you own copyrighted work and think your rights under U.S. copyright law have been infringed by anything on our site, the Digital Millennium Copyright Act means you can ask us to take it down. Here’s how to report it."
  },
  {
    "t": "h2",
    "text": "2. What you’re allowed to do on Panameer"
  },
  {
    "t": "p",
    "text": "You can only use our services for work and to learn from the information we share."
  },
  {
    "t": "p",
    "text": "Our site and services were made to be used for business, not for personal or consumer use. We run our marketplace to help users find each other, build working relationships, and make and receive payments for that work."
  },
  {
    "t": "p",
    "text": "You can also use some of our services to get information we think might be interesting and useful for our site visitors and users – like our Panameer blog. While we do our best to make sure that this information is timely and accurate, there might sometimes be mistakes. We don’t make any guarantees about information posted on our site, so never use it as tax or legal advice. And you should always doublecheck the information for yourself."
  },
  {
    "t": "h2",
    "text": "3. What you’re not allowed to do on Panameer"
  },
  {
    "t": "p",
    "text": "Certain uses of the site are not allowed. Here we go into much more depth about those things, including: posting unacceptable content (3.1) acting in a misleading or fraudulent way (3.2) treating others unfairly (3.3) abusing our feedback system (3.4) other uses that aren’t allowed (3.5) In short, you’re not allowed to use our services to do (or encourage others to do) anything that is illegal, fraudulent or harmful. If you don’t see something on one of the lists below, you shouldn’t assume it’s allowed. When in doubt, contact us to check."
  },
  {
    "t": "h3",
    "text": "3.1 Posting unacceptable content"
  },
  {
    "t": "p",
    "text": "You can’t offer, share, support or try to find anything that: is illegal or defamatory is violent, discriminatory or harassing, either generally or towards a specific person or group (or encourages others to be), including anyone who is part of a legally protected group is sexually explicit or related to sex work or escort services is in any way related to child exploitation would infringe on any intellectual property rights, including copyrights would violate our Terms of Service, another website’s terms of service, or any similar contract would go against professional or academic standards or policies – including improperly submitting someone else’s work as your own, or by ghost-writing essays, tests, or certifications involves purchasing or requesting a fake review or is connected in any way to making or sharing misleading content (like ‘deep fakes’ or ‘fake news’) which is intended to deceive others."
  },
  {
    "t": "h3",
    "text": "3.2 Acting in a misleading or fraudulent way"
  },
  {
    "t": "p",
    "text": "On Panameer, you can’t do anything that’s dishonest or meant to fool others."
  },
  {
    "t": "p",
    "text": "You can’t misrepresent yourself, your experience, skills or professional qualifications, or that of others."
  },
  {
    "t": "p",
    "text": "This includes: lying about your experience, skills or professional qualifications using generative AI or other tools to substantially bolster your job proposals or work product if such use is restricted by your client or violates any third-party's rights passing off any part of someone else’s profile or identity as your own using a profile picture that isn’t you, misrepresents your identity or is someone else impersonating or falsely attributing statements to any person or entity, including an Panameer representative or forum leader falsely claiming or implying you’re connected to a person or organization (including Panameer) – for example, you can’t say you work for a particular company when you don’t, and agencies can’t use a provider’s profile if they’ve stopped working together."
  },
  {
    "t": "p",
    "text": "Similarly, you must always be honest about who’s doing the work. That means you can’t: allow someone else to use your account, which misleads other users or falsely claim one provider will do a job when another will actually do it – including submitting a proposal on behalf of a provider who can’t or won’t do the work."
  },
  {
    "t": "p",
    "text": "We’re particularly invested in avoiding fraud and misrepresentations when it comes to payments. This means:"
  },
  {
    "t": "p",
    "text": "Providers can’t fraudulently charge a client in any way, including by: falsifying the hours, keystrokes or clicks recorded in the Panameer app reporting or billing time you haven’t actually worked reporting time worked by someone else and claiming you did the work demanding bribes or other payments without the intention of or without actually providing services in exchange for the payment."
  },
  {
    "t": "p",
    "text": "Clients can’t engage in fraud related to payments, including by: posting jobs with payment terms that are objectively unreasonable or disproportionate to the scope of services requested hiring themselves as providers and paying themselves demanding services without the intention of or without actually providing payment in exchange for the services."
  },
  {
    "t": "h3",
    "text": "3.3 Treating others unfairly"
  },
  {
    "t": "p",
    "text": "Everyone should be treated fairly and legally on Panameer."
  },
  {
    "t": "p",
    "text": "You can’t use Panameer to: express an unlawful preference in a job post or proposal unlawfully discriminate against someone incite or encourage violence post personal identifying information or other sensitive, private data about another person spam other users with proposals or invites. This includes posting the same job several times at once and contacting people you connected with on Panameer outside of Panameer without their permission make or demand bribes or payments for anything other than the work ask for or demand free work – you can’t ask providers to submit work for little or no payment as part of a proposal bid or competition request a fee in order to submit a proposal request or provide services that primarily concern making purchases on behalf of another, including the purchase of cryptocurrency or NFTs."
  },
  {
    "t": "h3",
    "text": "3.4 Abusing our feedback system"
  },
  {
    "t": "p",
    "text": "You must use our feedback system honestly and fairly."
  },
  {
    "t": "p",
    "text": "That means you can’t: withhold payment or work until you’ve been given positive feedback swap payment (or anything of value) for feedback, including with third parties coerce another user by threatening negative feedback use the system to share unrelated views (like about politics or religion) offer or accept fake services to improve your feedback or rating score, which is called feedback building hire and rate yourself."
  },
  {
    "t": "h3",
    "text": "3.5 Other uses that aren’t allowed"
  },
  {
    "t": "p",
    "text": "Panameer relies on technology and trust – here’s how we maintain those things."
  },
  {
    "t": "p",
    "text": "You can’t copy, share or give away your account. You can’t have multiple accounts and you can’t sell, trade or give your account to anyone else without our permission."
  },
  {
    "t": "p",
    "text": "You can’t go around us. In particular, you can’t talk to another user or ask for or share a way to get in touch - a means of direct contact - outside of Panameer before you’ve agreed to a Work Order. This means you can’t add your contact details to a job post, your profile, communications or other content. (There are exceptions to this for Enterprise clients.)"
  },
  {
    "t": "p",
    "text": "You can’t promote other organizations – including advertising any other websites, products or services. You also can’t use our site to recruit providers or clients to join another agency, website or company, unless you pay us a fee to do so. For more information, take a look at Section 7 of our User Agreement."
  },
  {
    "t": "p",
    "text": "You can't be a current or recent Panameer employee and use our site. By using our site, you confirm that you are not currently employed by Panameer or any of its subsidiaries, and that you have not been employed by them at any time during this calendar year or within the past six months."
  },
  {
    "t": "p",
    "text": "You can’t interfere with our technology or tamper with our site or services. That means you can’t: bypass any security features we’ve put in place to restrict how you use the site – you’re not allowed to try and get around restrictions on copying content interfere with or compromise our systems, server security, or transmissions use a robot, spider, scraper, or similar mechanisms on our site without written permission copy, distribute, or otherwise use any information you found on Panameer, if whether directly or through third parties (like search engines), without our consent (no scraping allowed) collect or use identifiable information, including account names) overwhelm the site with an unreasonable or large amount of information"
  },
  {
    "t": "p",
    "text": "introduce any malware or any other code or viruses that could harm us, our customers, or our services access our services through any technology other than our interface frame or link to the services without our written permission use our services to build a similar service, identify or poach our users or publish any performance or benchmark analysis relating to the site reverse engineer, decipher, modify, or take source code from our site that is not open source without our written permission."
  },
  {
    "t": "h2",
    "text": "4. Enforcing our terms of use"
  },
  {
    "t": "p",
    "text": "If you break any of these rules, we can suspend your account and stop you from using Panameer (4.1). If you see someone else breaking these rules, please let us know (4.2)."
  },
  {
    "t": "h3",
    "text": "4.1 We enforce these rules"
  },
  {
    "t": "p",
    "text": "We have the right to look into any potential violations of these terms of use, and might decide to pause, change or take away any content on our site when we do."
  },
  {
    "t": "p",
    "text": "We can’t guarantee that we’ll take action against every potential violation, but just because we don’t take action against one breach doesn’t waive our right to take action against any future breaches, whether they’re related to the first breach or not."
  },
  {
    "t": "p",
    "text": "If we do suspect rule-breaking, we can stop you using our site at any time. You may not be able to use any of our services if we disable or close your account, but you will still be responsible to pay for all services used before your account was closed. In addition, these things will continue: our rights to use and share your content and feedback (Section 1.4.2) our users’ and visitors' rights to share your content (Section 1.4.2) your agreement to all the rules outlined in Section 3 on this page."
  },
  {
    "t": "h3",
    "text": "4.2 Tell us if you see someone breaking these rules"
  },
  {
    "t": "p",
    "text": "What to do if you become aware of a violation of our Terms of Use."
  },
  {
    "t": "p",
    "text": "If you believe anyone is breaking any of our terms of use, please let our customer service team know or report it wherever you see this flag:"
  },
  {
    "t": "p",
    "text": "If we follow up on the breach, you agree to help with our investigation and take reasonable steps to help us fix the problem."
  },
  {
    "t": "h2",
    "text": "5. Definitions"
  },
  {
    "t": "p",
    "text": "Here, we explain some of the terms we’ve used in our Terms of Use. Any other terms in italics should be defined when they’re mentioned, in the User Agreement or Terms of Service."
  },
  {
    "t": "p",
    "text": "An affiliate is anyone or anything that in any way manages, is managed by, or shares management with us."
  },
  {
    "t": "p",
    "text": "A client is someone using our site to find provider services from another user."
  },
  {
    "t": "p",
    "text": "A deep fake is a video or image that has been changed to replace one person with another in a deliberately misleading way, without asking the person whose face has been used."
  },
  {
    "t": "p",
    "text": "A provider is an individual or agency using our site to offer their services to clients."
  },
  {
    "t": "p",
    "text": "Provider services refer to the work providers do on Panameer."
  },
  {
    "t": "p",
    "text": "A means of direct contact is information that would let someone get in touch with you directly (or find the information to do that) so you can bypass our site. For example, phone numbers, email and physical addresses, social media accounts, and personal websites with contact information are means of direct"
  },
  {
    "t": "p",
    "text": "contact."
  },
  {
    "t": "p",
    "text": "Site services are all services, applications and products – apart from provider services – that people can access through Panameer."
  },
  {
    "t": "p",
    "text": "Content is what users post to Panameer themselves, like comments, profiles, feedback, images, or other information. It includes anything posted by you even if elements of the content were originally generated by generative AI or other tools, or in response to questions posed to you by Panameer or other users or Panameer."
  }
];
