#!/usr/bin/env python3
"""
Users.xlsx -> prisma/seed-data/test-users.json

Same edge as the catalog build (scripts/build-service-catalog-v5.py): the
spreadsheet stays the thing Scott edits, the JSON stays the thing the seeder
reads, and this script is the only translation between them. A TS seeder cannot
read xlsx, and hand-transcribing names and logins into TypeScript is how a test
account ends up existing in the code and not in the sheet.

    python3 scripts/build-test-users.py
"""
import json, os, sys
try:
    import openpyxl
except ImportError:
    sys.exit("openpyxl is required:  pip3 install openpyxl")

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
XLSX = os.path.normpath(os.path.join(REPO, "..", "4. Project Documents", "4. Decide", "Users.xlsx"))
OUT = os.path.join(REPO, "prisma", "seed-data", "test-users.json")

def rows(ws, header_row):
    hdr = [str(c.value).strip() if c.value else "" for c in ws[header_row]]
    for r in ws.iter_rows(min_row=header_row + 1, values_only=True):
        if not any(v not in (None, "") for v in r):
            continue
        yield {hdr[i]: (str(v).strip() if v is not None else "") for i, v in enumerate(r) if i < len(hdr)}

def clean(v):
    return (v or "").strip()

wb = openpyxl.load_workbook(XLSX, data_only=True)
out = {"_source": "4. Project Documents/4. Decide/Users.xlsx",
       "_note": "Generated by scripts/build-test-users.py; do not hand-edit.",
       "admins": [], "buyers": [], "sellers": [], "spec": []}

for r in rows(wb["Admins"], 2):
    email = clean(r.get("Username"))
    if "@" not in email: continue
    out["admins"].append({"pid": clean(r.get("PID")), "name": clean(r.get("Person")),
                          "email": email, "password": clean(r.get("Password")) or "Panameer123"})

for r in rows(wb["Buyers"], 2):
    email = clean(r.get("Username"))
    if "@" not in email: continue
    out["buyers"].append({"pid": clean(r.get("UID")), "name": clean(r.get("Person")),
                          "email": email, "password": clean(r.get("Password")) or "Panameer123",
                          "company": clean(r.get("Company")), "job": clean(r.get("USER_JOB"))})

for r in rows(wb["Sellers"], 2):
    email = clean(r.get("Username/Login"))
    if "@" not in email: continue
    out["sellers"].append({"pid": clean(r.get("PID")), "name": clean(r.get("Person")),
                           "email": email, "password": clean(r.get("Password")) or "Panameer123",
                           "team": clean(r.get("Team")), "job": clean(r.get("User Job")),
                           "role": clean(r.get("Role")), "software": clean(r.get("Domain/Software")),
                           "skills": clean(r.get("Skills"))})

# The v2 spec sheet carries the richer provider profile (headline, validated,
# counts, rate, location) that WS-2 needs to build a believable card.
for r in rows(wb["Test Set v2 (spec)"], 1):
    login = clean(r.get("Login (sw_user)"))
    if "@" not in login: continue
    out["spec"].append({"pid": clean(r.get("PID")), "name": clean(r.get("Name")), "email": login,
                        "cls": clean(r.get("Class")), "lens": clean(r.get("Role Lens")),
                        "suite": clean(r.get("Application / Suite")), "domain": clean(r.get("Domain")),
                        "headline": clean(r.get("Headline (<=42)")), "validated": clean(r.get("Validated")),
                        "employers": clean(r.get("Employers")), "projects": clean(r.get("Projects")),
                        "rate": clean(r.get("Rate")), "location": clean(r.get("Location"))})

# De-dupe on email, keeping the LAST row — the v2 test set is appended below the
# originals, so the newer definition wins.
for k in ("admins", "buyers", "sellers"):
    seen = {}
    for x in out[k]:
        seen[x["email"].lower()] = x
    out[k] = list(seen.values())

with open(OUT, "w", encoding="utf-8") as f:
    json.dump(out, f, indent=2, ensure_ascii=False)
    f.write("\n")
print(f"admins  {len(out['admins'])}\nbuyers  {len(out['buyers'])}\nsellers {len(out['sellers'])}\nspec    {len(out['spec'])}\n-> {OUT}")
